### ISSUE TITLE
request password issue 

### ISSUE THREAD

**Issue by mhhonline** [akveo/ngx-admin-bundle-support#15]
Greetings, 

I have bought "ngx-admin Backend Bundle Node + E-comm"

for a user request to get the password
http://localhost:4200/auth/request-password

The returned URL is http://localhost:4200/#/auth/reset-password?reset_password_token=7bf2f30…..
you can see the ‘#’ casing the URL broken. If the ‘/#’ is removed, it opens the right page and then I can reset my password. 

fixed need to be applied into sendResetPasswordEmail on EmailServices.js

Question: How can I send an actual email to the user? 

Regards,
Mohammed

**Comment by valentinkononov** [comment]
Hi Mohammed! Thanks for this issue. 

Initially, we designed node api in a minimalistic way, without actual email sending. Probably it will be added in the nearest future, but initial idea is to give a backbone of node api working with ngx-admin, so that client can add / implement needed features by himself. 

But I recommend to use [SendGrid](https://sendgrid.com/docs/for-developers/sending-email/v3-nodejs-code-example/) library, one of the most popular and proven email senders for node.

Thanks! I'm closing the issue but I will make sure we have emails sending in the backlog.

**Comment by mhhonline** [comment]
thank you very much I will check the suggested lib and compare it with https://nodemailer.com/about/

thanks

**Comment by JGMAGNO** [comment]
why it is needed to logged-in in order to reset the password?
I am accessing the reset link that is being sent to my email, nothing happens when you're logged-out, It needs to be logged-in before you reset the password.

**Comment by tanujlight** [comment]
> why it is needed to logged-in in order to reset the password? I am accessing the reset link that is being sent to my email, nothing happens when you're logged-out, It needs to be logged-in before you reset the password.

I am also facing the same issue 
any update on this?
