### ISSUE TITLE
Django Bundle not going to home page

### ISSUE THREAD

**Issue by anbalaganr** [akveo/ngx-admin-bundle-support#5]

**Comment by anbalaganr** [comment]
Dijango bundle not going to home page after successfull login. It says "You have been successfully logged in." and stay in same login page

**Comment by anbalaganr** [comment]
Any updates???

**Comment by jcanning** [comment]
Hi, i just purchased this and with great difficulties, finally got everything to load to only have the same error as @anbalaganr above. 18 Days and no response is not good for paying customers. Please let us know what the next steps are.

**Comment by valentinkononov** [comment]
Dear all! Thanks for your requests and sorry for such inconvenient delay. At the moment, this issue was fixed and updated bundle works fine. Issue was related to incorrect role checking of user, that's the reason of not routing to other pages. 
Please let us know if you have any issues with the lates code.
Latest bundle version can be downloaded via the link in your email or in shopify

**Comment by valentinkononov** [comment]
For those who cannot update for any reason, please remove usage of [**AdminGuard**] everywhere in routing, as well as usage of directive ***nbIsGranted* or **accessChecker** service.
